### ISSUE TITLE
This adversely affects the default show_files command - default shows opened files, this shows ALL files...

### ISSUE THREAD

**Issue by Acecool** [lite3/Sublime-QuickGotoAnything#3]
I want a way to show only the opened files so I bound f1 to
{ "keys": ["f1"], "command": "show_overlay", "args": {"overlay": "goto", "show_files": true} },

And it worked until I installed QuickGotoAnything ( because it had a function list - the var list leaves a LOT to be desired because it doesn't ignore comments ) ) - now ALL files in the project show up in the list which isn't what I want...

Additionally, when I use the SEARCH option in the file list, it gives me a cyan number to the left like 247, or 90 or whatever- I thought this was the number of times a word appeared in a file, but that doesn't seem to be the case.. But high numbers show up even if the word has nothing to do with the file so what Is this about?

**Comment by litefeel** [comment]
@Acecool 
Thanks for your feedback.
I added `show_files` param in version 1.2.2, and default is true.

The cyan number, it represent that how similar the text of item and above text.
